### ISSUE TITLE
IHO C17 Review

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-iho#44]
*This ticket is related to https://github.com/metanorma/mn-samples-iho/issues/30*

I have noticed these two issues:

* "Annex I" renders as "Annex J" in generated document. @anermina could you confirm this when you can, please?

*Original:*
![diff1-pdf](https://user-images.githubusercontent.com/33627611/82595638-f019fa00-9b73-11ea-8ccf-ef6f1b10497e.PNG)

*Generated:*
![diff1-doc](https://user-images.githubusercontent.com/33627611/82595643-f27c5400-9b73-11ea-9376-ce3b156dbde5.PNG)

* Footnote 10 (`footnote:[http://inspire.ec.europa.eu/]`) is not shown in generated version. At least not on the page where it is referenced. Such footnote is duplicated with footnote 1 in .adoc source, so it gets referenced with footnote number 1.

*Original:*
![diff2-pdf](https://user-images.githubusercontent.com/33627611/82596577-7f73dd00-9b75-11ea-9f4d-eb540111f5c3.PNG)

*Generated:*
![diff2-doc](https://user-images.githubusercontent.com/33627611/82596587-8569be00-9b75-11ea-8178-7964a4090f0c.PNG)

**Comment by anermina** [comment]
> "Annex I" renders as "Annex J" in generated document. @anermina could you confirm this when you can, please?

Yes, I also noticed this. However, IHO is in alpha phase, so I didn't report it as an issue now. Source .adoc is correct here.

> Footnote 10 (footnote:[http://inspire.ec.europa.eu/]) is not shown in generated version. At least not on the page where it is referenced. Such footnote is duplicated with footnote 1 in .adoc source, so it gets referenced with footnote number 1.

This actually regularly happens when footnote is repeated. At least I saw this in other generated documents as well, while some of the originals duplicate the footnote assigning it a different number, so it can appear on the page where that footnote is set. I'm not sure which rule does IHO want to apply for the footnotes.

**Comment by ronaldtse** [comment]
Posted both issues!

**Comment by manuelfuenmayor** [comment]
Thanks @ronaldtse ! So, I think there is no need to track this ticket anymore. Closing.
